### PR TITLE
[Settings] Add Stream Deck Panel. Add Checkbox options for showing warning message

### PR DESCRIPTION
**Pull request by Mutex666**
- Add a Stream Deck settings panel.
- Add a "ShowWarning" checkbox.
    - This was a little thing that bothered me: Every time I launched the software, if `-NoStreamDeck` was set, the warning message always appeared, even with `-StartMinimized`. Since I didn't want to remove a feature, I added a checkbox in the setting to show or not this message. Even if you don't find this interesting or want to manage this warning message another way, at least the Stream Deck settings page could maybbe useful in the future ?
- Made some light refacto on the page, used auto-properties to reduce the code size and rationalized a little the event handlers.

Don't feel obliged to merge if the changes doesn't please you , I won't be mad at all. That's why PRs are made for ;-)

### CODE REVIEW

**Comment by jdahlblom** [comment]
OK so the warning had a bug, it shouldn't show the warning of -NoStreamDeck was used. It was a simple boolean bug in an if statement.

**Comment by jdahlblom** [comment]
The problem with these settings are that they are nullified as soon as you update DCSFP since there isn't an installation part. And having proper installation isn't viable since the quality of the releases are what they are. Some releases have fatal flaws which would make it a nightmare for the user. So better have it like this.
I have thought about having an optional environment variable pointing out a settings file that would always be used but haven't come around making it.

**Review by jdahlblom — CHANGES_REQUESTED** [review]
If you could remove the setting for Stream Deck warning dialog and keep the rest of the refactoring. As I mentioned it was a bug that caused the warning to show even if you used -NoStreamDeck.

**Comment by Mutex666** [comment]
Hi,  quick changes following your remarks. I only left the refactoring and removed everything related to Stream Deck, including the stack panel.

**Pull request merged**
